server:
  port: 8080

spring:
  datasource::
    url: jdbc:mysql://host.docker.internal:13306/user?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1  # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: create # 오직 테스트 환경에서만
    generate-ddl: true # 오직 테스트 환경에서만
    show-sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: host.docker.internal:9092

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 하트비트 간격(기본 30초)
    lease-expiration-duration-in-seconds: 30  # 만료 시간(기본 90초)
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/

feign:
  client:
    config:
      default:  # 모든 Feign 클라이언트에 적용되는 기본 설정
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

jwt:
  expires-in: 86400 # default 1day
  mobile-expires-in: 31536000
  table-expires-in: 31536000
  secret-key: AADfaskllew32dsfasdTG764Gdslkj298GsWg86Gkalsdjfalkdsjfkladsjfklasdjfkwejqtklfksadnfklsadjmfkl
